### ISSUE TITLE
Github linked account

### ISSUE THREAD

**Issue by caseyprovost** [engineyard/ey-docs#101] opened 2011-08-20 00:37 UTC
I have followed the instructions at: http://docs.engineyard.com/linking-github-to-appcloud.html#topic2 and I cannot deploy. Each time it states: Permission denied (publickey). If it is linked why is this not working?

**Comment by janeday** [comment] 2011-08-20 00:58
Hi Casey,

I'm very sorry that this isn't working for you. Please log an Engine Yard support ticket for this so the experts can help figure out the problem.  

Thanks for letting me know. 

Sincerely,

Jane Day

---

Jane Day | jday@engineyard.com | 415.624.8435
Sr. Tech Writer | Engine Yard

**Comment by caseyprovost** [comment] 2011-08-20 01:00
I have, but I believe it is after support hours so unfortunately I am out of luck. Guess my bug fixes will have to wait till tomorrow.

## 

Casey Provost
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by BrittTheIsh** [comment] 2011-08-22 18:36
Casey, do you indeed have a ticket assigned for this issue at https://support.cloud.engineyard.com ?  I submitted your issue with our Engineering team on Friday evening.  They're looking into the issue at the moment.  Can you please provide your ticket # so we can continue this discussion there.

**Comment by janeday** [comment] 2011-08-22 18:48
Thanks for responding to this. I'll be interested to know what the problem is and if there is anything we need to add to the doc about it.
jane

On Aug 22, 2011, at 11:36 AM, BrittTheIsh wrote:

> Casey, do you indeed have a ticket assigned for this issue at https://support.cloud.engineyard.com ?  I submitted your issue with our Engineering team on Friday evening.  They're looking into the issue at the moment.  Can you please provide your ticket # so we can continue this discussion there.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/engineyard/ey-docs/issues/101#issuecomment-1872958

---

Jane Day | jday@engineyard.com | 415.624.8435
Sr. Tech Writer | Engine Yard

**Comment by caseyprovost** [comment] 2011-08-23 18:45
The problem is ticketed and resides here: request #28105, it looks like it is due to my adding of some environment conditions to my gemfile and gemfile.lock not being updated....will keep working on it though

**Comment by BrittTheIsh** [comment] 2011-08-23 18:52
Thanks for the ticket #.  I'm going to close this issue in favor of supporting you through our ticketing system.  Thank you for bringing this to our attention.

**Comment by caseyprovost** [comment] 2011-08-23 18:52
thank you

## 

Casey Provost
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Closed as completed by BrittTheIsh** 2011-08-23 18:52 UTC
